dist: precise
git:
  depth: 1
language: ruby
cache:
  apt: true
  directories:
    - vendor/bundle
    - $HOME/.cache/pip
sudo: required
addons:
  apt:
    packages:
      - haveged
python:
  - 2.7
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-1.7.27
#  - jruby-head
gemfile:
  - Gemfile
  - Gemfile.master
before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
#  - gem update --system
#  - gem --version
  - gem install bundler
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq graphviz
  - sudo apt-get install -qq python-gtk2 python-cairo
  - sudo apt-get install -qq ttf-dejavu
  - export BLOCKDIAG_FONTPATH=/usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf
  - pip install --user -r pip-requirements.txt -c pip-constraints.txt
  - bundle install --path vendor/bundle --jobs=3 --retry=3
  - npm install -g mermaid.cli
  - npm install -g wavedrom-cli
  - sudo apt-get install -qq imagemagick
# Install umlet
  - curl -s -O http://www.umlet.com/umlet_14_2/umlet-standalone-14.2.zip
  - unzip -qq umlet-standalone-14.2.zip
  - cp Umlet/umlet.sh Umlet/umlet
  - chmod +x Umlet/umlet
  - export PATH=$PATH:$PWD/Umlet/
  - sudo apt-get install -qq mscgen