---
version: "{build}"
branches:
  only:
    - master
clone_depth: 10
install:
  - set PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - echo %ChocolateyInstall%
  - set PATH=C:\ProgramData\chocolatey\bin;%PATH%
  # https causes certificate verification errors
  # Updating rubygems resolves this, but then gem install seems to hang for unknown reasons
  # Use http instead as a workaround
  # - gem update --system
  - gem sources -r https://rubygems.org/
  - gem install bundler --source http://rubygems.org/
  - bundle install
  - cinst graphviz.portable
#  - ps: (new-object net.webclient).DownloadFile('https://github.com/ErwinJanssen/graphviz/releases/download/v2.38/graphviz-2.38.msi', 'graphviz.msi')
#  - ps: msiexec /i graphviz.msi /qn /norestart
#  - set PATH=C:\Program Files (x86)\Graphviz2.38\bin;%PATH%
  - cinst imagemagick.tool
  - cinst gnuplot
  - npm install -g nomnoml
  - npm install -g mermaid.cli
  - npm install -g wavedrom-cli
# Install umlet
  - curl -s -O http://www.umlet.com/umlet_14_2/umlet-standalone-14.2.zip
  - 7z x umlet-standalone-14.2.zip
  - set PATH=%PATH%;%cd%\umlet  
build_script:
  - echo %PATH%
  - bundle exec rake package
test_script:
  - bundle exec rake test
artifacts:
  - path: pkg\*.gem

environment:
  matrix:
    - ruby_version: "25"
    - ruby_version: "24"
    - ruby_version: "23"
